[[constraint]]
  name = "github.com/gorilla/csrf"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
